services:
  - type: web
    name: api-agroecologia
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_agroecologia_fastapi:app --host 0.0.0.0 --port 10000"
